[loadbalancer]
lb-01 ansible_host=<LB_PUBLIC_IP> ansible_user=azureuser
# Ganti <LB_PUBLIC_IP> dengan nilai dari: terraform output lb_public_ip

[frontend_workers]
wk-01 ansible_host=10.0.1.10 ansible_user=azureuser
wk-02 ansible_host=10.0.1.11 ansible_user=azureuser

[backend_workers]
wk-03 ansible_host=10.0.1.20 ansible_user=azureuser
wk-04 ansible_host=10.0.1.21 ansible_user=azureuser

[workers:children]
frontend_workers
backend_workers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
