[loadbalancer]
lb-01 ansible_host=4.194.67.9 ansible_user=azureuser
# Ganti <LB_PUBLIC_IP> dengan terraform output lb_public_ip

[frontend_workers]
wk-01 ansible_host=10.0.1.10 ansible_user=azureuser

[backend_workers]
wk-02 ansible_host=10.0.1.11 ansible_user=azureuser

[workers:children]
frontend_workers
backend_workers

[workers:vars]
# Meneruskan koneksi melalui Load Balancer dan secara eksplisit memberikan private key ke sesi SSH jump host
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q azureuser@4.194.67.9 -o StrictHostKeyChecking=no -i ~/.ssh/ticketing_key"'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
