---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create SSL directory
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate self-signed SSL certificate
  command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout /etc/nginx/ssl/nginx.key
    -out /etc/nginx/ssl/nginx.crt
    -subj "/C=ID/ST=Jakarta/L=Jakarta/O=TiketKonser/OU=DevOps/CN=4.194.67.9"
  args:
    creates: /etc/nginx/ssl/nginx.crt


- name: Deploy Nginx configuration from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: Reload Nginx

- name: Validate Nginx configuration
  command: nginx -t
  changed_when: false

- name: Ensure Nginx is started and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes
